### ISSUE TITLE
Anchor link highlight style does not perform well in dark mode

### ISSUE THREAD

**Issue by scholar7r** [hanwenguo/hugo-theme-nostyleplease#39]
![Works_In_Light_Mode](https://github.com/user-attachments/assets/b5031512-98a2-42a5-92a7-5b39251a679f)

![Works_In_Dark_Mode](https://github.com/user-attachments/assets/786b16df-095d-4857-9386-188132bbe05e)

As shown in the figure, the anchor link in highlighted state is difficult to observe when displayed in dark mode. Anchor links in highlighted state need to display text with different foreground colors.

**Comment by scholar7r** [comment]
Modify the scss file `assets/css/main.scss` to fix this

```scss
@mixin dark-appearance {
  @include theme(#212121, #fafafa, #000000, #0071bc, #a359e9, #FFFF00);

  *:target {
    background: #444444;
    color: #ffff00;
  }
}

@mixin light-appearance {
  @include theme(#ffffff, #212121, #666666, #1e70bf, #921292, #FFFF00);

  *:target {
    background: #ffffcc;
    color: #212121;
  }
}
```
